# Generated by Django 4.1.2 on 2022-11-08 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bid_value', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('submitted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.paper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reviewer')),
            ],
            options={
                'db_table': 'bid',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('rating', models.IntegerField()),
                ('submitted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.bid')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.reviewer')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.RemoveField(
            model_name='paperreview',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='paperreview',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_desc',
            field=models.TextField(default='Please enter description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.author'),
        ),
        migrations.AlterField(
            model_name='paperauthor',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.paper'),
        ),
        migrations.DeleteModel(
            name='PaperBid',
        ),
        migrations.DeleteModel(
            name='PaperReview',
        ),
    ]
