# Generated by Django 4.1.2 on 2022-11-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bid_review_remove_paperreview_paper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.paper')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.review')),
            ],
            options={
                'db_table': 'paper_review',
            },
        ),
    ]
