# Generated by Django 4.1.2 on 2022-11-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='paper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.paper'),
            preserve_default=False,
        ),
    ]
