# Generated by Django 4.1.2 on 2022-11-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_comment_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.paper'),
        ),
    ]
